import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import '@/assets/css/globals.scss';
import type React from 'react';

import SidebarProvider from '@/lib/zustand/SidebarStore';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const outfit = Outfit({
  subsets: ['latin'],
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement => (
  <html lang="en">
    <body className={`${outfit.className} dark:bg-gray-900`}>
      <SidebarProvider>{children}</SidebarProvider>
    </body>
  </html>
);

export default RootLayout;
